version: '3'

services:
  ph7_4:
    image: php:7.4-fpm
    container_name: my-php7_4-container
    working_dir: /var/www/html
    ports:
      - "9022:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_0:
    image: php:8.0-fpm
    container_name: my-php8_0-container
    working_dir: /var/www/html
    ports:
      - "9023:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_1:
    image: php:8.1.25-fpm
    container_name: my-php8_1-container
    working_dir: /var/www/html
    ports:
      - "9024:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_2:
    image: php:8.2.12-fpm
    container_name: my-php8_2-container
    working_dir: /var/www/html
    ports:
      - "9025:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_3:
    image: php:8.3-fpm
    container_name: my-php8_3-container
    working_dir: /var/www/html
    ports:
      - "9026:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_4:
    image: php:8.4-fpm
    container_name: my-php8_4-container
    working_dir: /var/www/html
    ports:
      - "9027:80"
    volumes:
      - ./tests:/var/www/html/tests

  php8_5:
    image: php:8.5-fpm
    container_name: my-php8_5-container
    working_dir: /var/www/html
    ports:
      - "9028:80"
    volumes:
      - ./tests:/var/www/html/tests